### ISSUE TITLE
dial back validation a bit

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/package_config#121]
I believe we're failing - on validation - for URLs which are valid. Here's a failure I see:

```
Invalid argument (root): In package analyzer_plugin: Not an absolute URI with no query or fragment with a path ending in /: "/Users/devoncarew/projects/dart-lang/sdk/sdk/pkg/analyzer_plugin"
#0      throwError (package:package_config/src/errors.dart:32:35)
#1      SimplePackage.validate (package:package_config/src/package_config_impl.dart:234:14)
#2      new Package (package:package_config/src/package_config.dart:239:21)
#3      makePackageConfigs (file:///Users/devoncarew/projects/dart-lang/sdk/sdk/tools/generate_package_config.dart:129:11)
...
```

We're looking for a path ending in in `/`, but the path I'm passing in is one we see generated from most of our APIs (File.uri, File.path, packahe:path absolute(), ...).

**Comment by natebosch** [comment]
> the path I'm passing in is one we see generated from most of our APIs (File.uri, File.path, packahe:path absolute(), ...).

We wouldn't want to use `File.uri` right? It should come from a `Directory.uri` which would include a trailing `/`.

I do think it's sensible to treat a trailing `/` as optional when the input is coming from a user, I'm less sure about something like this where we expect it to be generated.

Can you elaborate on the specific code you were using to generate the path which didn't include the trailing `/` automatically?

**Comment by jakemac53** [comment]
Fwiw [the spec](https://github.com/dart-lang/language/blob/master/accepted/2.8/language-versioning/package-config-file-v2.md) does say that a trailing `/` should be inserted if not provided:

```
 If the resolved URI does not end with a / (signaling that it is a directory), a / is appended.
```

This line is present for both the `rootUri` and `packageUri` fields.

**Comment by lrhn** [comment]
The trailing slash is added to the model when read from a `package_config.json` file without the slash.
The model insists on a trailing slash, which is likely why it's rejecting input without one.
It could just add a missing slash instead.

**Comment by devoncarew** [comment]
> We wouldn't want to use File.uri right? It should come from a Directory.uri which would include a trailing /.

Yup - I should have said `Directory.uri` above. Experimenting again with this, I do see that Directory.uri has a trailing slash. I think what I was doing was using a combo of package:path and `Uri.resolve(String)` to generate URIs. I ended up having to wrap the input into the `Package` constructor with something like `_potentiallyAddTrailingSlash`, which wasn't very ergonomic.

Here is something that'll throw:

```
var parent = Directory.current;
var package = Package('foo', parent.uri.resolve('bar')); // throws
```

> Can you elaborate on the specific code you were using to generate the path which didn't include the trailing / automatically?

I don't have the code around anymore - I was working to generate the SDK's package_config file. I ended up not using this package - the file's generated in a bootstrapping phase, so I couldn't refer to other packages.

> Fwiw the spec does say that a trailing / should be inserted if not provided:

It sounds like we could just replace the validation logic w/ code to append any necessary trailing slashes.

**Comment by natebosch** [comment]
> I ended up having to wrap the input into the `Package` constructor with something like `_potentiallyAddTrailingSlash`, which wasn't very ergonomic.

It sounds like you mainly had a difference of opinion on whether we should need to be careful at each usage site. The intended design was strict on purpose. I don't have a particularly strong opinion on whether we should be strict on purpose in this case (the intended audience for that API is not very wide). FWIW I do think that it's an OK outcome for us to be strict in _this_ package, and for packages which prefer leniency to workaround with a `_ensureTrailingSlash` or `_ensureDirectoryUri`.

> Here is something that'll throw:

The intention would be to have written

```
var parent = Directory.current;
var package = Package('foo', parent.uri.resolve('bar/'));
```

because we should be resolving a directory to meet the demands of the API.
